### PR TITLE
(GH-1) Added method for clearing build cache

### PR DESCRIPTION
**Pull request by gep13**
Relates to #1

### CODE REVIEW

**Comment by gep13** [comment]
@Redth Let me know what you think of this.  Thanks!

**Comment by Redth** [comment]
Not sure why my tests (unrelated) were failing but this looks good thanks :)

**Comment by gep13** [comment]
@Redth  Sweet, thank you very much!  Do you know when you will be in a position to push a new version to nuget?  Thanks!

**Comment by Redth** [comment]
Pushed!

**Comment by gep13** [comment]
>@Redth said...
Pushed!

What a guy! Thank you.

**Pull request merged**
